name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build_container:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Auth Docker
        id: auth_docker
        run: gcloud auth configure-docker ${{ vars.ARTIFACT_REGISTRY_HOSTNAME }}
          
      - name: Build and push kanban app
        uses: docker/build-push-action@v4
        with:
          context: ./kanban-app
          push: true
          tags: qthompson/kanban-app:latest
          

      - name: Build and push kanban ui
        uses: docker/build-push-action@v4
        with:
          context: ./kanban-ui
          push: true
          tags: qthompson/kanban-ui:latest