name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push kanban app
        uses: docker/build-push-action@v4
        with:
          context: ./kanban-app
          push: true
          tags: qthompson/kanban-app:latest
          

      - name: Build and push kanban ui
        uses: docker/build-push-action@v4
        with:
          context: ./kanban-ui
          push: true
          tags: qthompson/kanban-ui:latest